// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Channel int32

const (
	Channel_REGISTER  Channel = 0
	Channel_FACEBOOK  Channel = 1
	Channel_WHATSAPP  Channel = 2
	Channel_INSTAGRAM Channel = 3
	Channel_WECHART   Channel = 4
	Channel_QQ        Channel = 5
)

var Channel_name = map[int32]string{
	0: "REGISTER",
	1: "FACEBOOK",
	2: "WHATSAPP",
	3: "INSTAGRAM",
	4: "WECHART",
	5: "QQ",
}

var Channel_value = map[string]int32{
	"REGISTER":  0,
	"FACEBOOK":  1,
	"WHATSAPP":  2,
	"INSTAGRAM": 3,
	"WECHART":   4,
	"QQ":        5,
}

func (x Channel) String() string {
	return proto.EnumName(Channel_name, int32(x))
}

func (Channel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

type Type int32

const (
	Type_MANAGEMENT       Type = 0
	Type_SHORT_URL        Type = 1
	Type_LEARNING_ENGLISH Type = 2
	Type_BATTLE_OF_TANK   Type = 3
)

var Type_name = map[int32]string{
	0: "MANAGEMENT",
	1: "SHORT_URL",
	2: "LEARNING_ENGLISH",
	3: "BATTLE_OF_TANK",
}

var Type_value = map[string]int32{
	"MANAGEMENT":       0,
	"SHORT_URL":        1,
	"LEARNING_ENGLISH": 2,
	"BATTLE_OF_TANK":   3,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

type AddRequest struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Channel              Channel  `protobuf:"varint,3,opt,name=channel,proto3,enum=user.Channel" json:"channel,omitempty"`
	Type                 Type     `protobuf:"varint,4,opt,name=type,proto3,enum=user.Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRequest) Reset()         { *m = AddRequest{} }
func (m *AddRequest) String() string { return proto.CompactTextString(m) }
func (*AddRequest) ProtoMessage()    {}
func (*AddRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *AddRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRequest.Unmarshal(m, b)
}
func (m *AddRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRequest.Marshal(b, m, deterministic)
}
func (m *AddRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRequest.Merge(m, src)
}
func (m *AddRequest) XXX_Size() int {
	return xxx_messageInfo_AddRequest.Size(m)
}
func (m *AddRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRequest proto.InternalMessageInfo

func (m *AddRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *AddRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddRequest) GetChannel() Channel {
	if m != nil {
		return m.Channel
	}
	return Channel_REGISTER
}

func (m *AddRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_MANAGEMENT
}

type UpdateRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LoginName            string   `protobuf:"bytes,2,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Channel              Channel  `protobuf:"varint,4,opt,name=channel,proto3,enum=user.Channel" json:"channel,omitempty"`
	Type                 Type     `protobuf:"varint,5,opt,name=type,proto3,enum=user.Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRequest) Reset()         { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()    {}
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRequest.Unmarshal(m, b)
}
func (m *UpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRequest.Merge(m, src)
}
func (m *UpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRequest.Size(m)
}
func (m *UpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRequest proto.InternalMessageInfo

func (m *UpdateRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *UpdateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateRequest) GetChannel() Channel {
	if m != nil {
		return m.Channel
	}
	return Channel_REGISTER
}

func (m *UpdateRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_MANAGEMENT
}

type EnableRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableRequest) Reset()         { *m = EnableRequest{} }
func (m *EnableRequest) String() string { return proto.CompactTextString(m) }
func (*EnableRequest) ProtoMessage()    {}
func (*EnableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *EnableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableRequest.Unmarshal(m, b)
}
func (m *EnableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableRequest.Marshal(b, m, deterministic)
}
func (m *EnableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableRequest.Merge(m, src)
}
func (m *EnableRequest) XXX_Size() int {
	return xxx_messageInfo_EnableRequest.Size(m)
}
func (m *EnableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableRequest proto.InternalMessageInfo

func (m *EnableRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DisableRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableRequest) Reset()         { *m = DisableRequest{} }
func (m *DisableRequest) String() string { return proto.CompactTextString(m) }
func (*DisableRequest) ProtoMessage()    {}
func (*DisableRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *DisableRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableRequest.Unmarshal(m, b)
}
func (m *DisableRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableRequest.Marshal(b, m, deterministic)
}
func (m *DisableRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableRequest.Merge(m, src)
}
func (m *DisableRequest) XXX_Size() int {
	return xxx_messageInfo_DisableRequest.Size(m)
}
func (m *DisableRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisableRequest proto.InternalMessageInfo

func (m *DisableRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type LoginRequest struct {
	LoginName            string   `protobuf:"bytes,1,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Channel              Channel  `protobuf:"varint,3,opt,name=channel,proto3,enum=user.Channel" json:"channel,omitempty"`
	Type                 Type     `protobuf:"varint,4,opt,name=type,proto3,enum=user.Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *LoginRequest) GetChannel() Channel {
	if m != nil {
		return m.Channel
	}
	return Channel_REGISTER
}

func (m *LoginRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_MANAGEMENT
}

type ListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRequest) Reset()         { *m = ListRequest{} }
func (m *ListRequest) String() string { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()    {}
func (*ListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *ListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRequest.Unmarshal(m, b)
}
func (m *ListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRequest.Marshal(b, m, deterministic)
}
func (m *ListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRequest.Merge(m, src)
}
func (m *ListRequest) XXX_Size() int {
	return xxx_messageInfo_ListRequest.Size(m)
}
func (m *ListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRequest proto.InternalMessageInfo

type Response struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UserResponse struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Body                 []*User  `protobuf:"bytes,2,rep,name=body,proto3" json:"body,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Extra                *Extra   `protobuf:"bytes,4,opt,name=extra,proto3" json:"extra,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserResponse) GetBody() []*User {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *UserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *UserResponse) GetExtra() *Extra {
	if m != nil {
		return m.Extra
	}
	return nil
}

type User struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LoginName            string               `protobuf:"bytes,2,opt,name=loginName,proto3" json:"loginName,omitempty"`
	Password             string               `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Channel              Channel              `protobuf:"varint,4,opt,name=channel,proto3,enum=user.Channel" json:"channel,omitempty"`
	Type                 Type                 `protobuf:"varint,5,opt,name=type,proto3,enum=user.Type" json:"type,omitempty"`
	Status               bool                 `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedTime          *timestamp.Timestamp `protobuf:"bytes,7,opt,name=createdTime,proto3" json:"createdTime,omitempty"`
	LastModifiedTime     *timestamp.Timestamp `protobuf:"bytes,8,opt,name=lastModifiedTime,proto3" json:"lastModifiedTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetLoginName() string {
	if m != nil {
		return m.LoginName
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetChannel() Channel {
	if m != nil {
		return m.Channel
	}
	return Channel_REGISTER
}

func (m *User) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_MANAGEMENT
}

func (m *User) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *User) GetCreatedTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedTime
	}
	return nil
}

func (m *User) GetLastModifiedTime() *timestamp.Timestamp {
	if m != nil {
		return m.LastModifiedTime
	}
	return nil
}

type Extra struct {
	TotalCount           int64    `protobuf:"varint,1,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	CurrentPage          int64    `protobuf:"varint,2,opt,name=currentPage,proto3" json:"currentPage,omitempty"`
	TotalPages           int64    `protobuf:"varint,3,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	IsFirst              bool     `protobuf:"varint,4,opt,name=isFirst,proto3" json:"isFirst,omitempty"`
	IsLast               bool     `protobuf:"varint,5,opt,name=isLast,proto3" json:"isLast,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Extra) Reset()         { *m = Extra{} }
func (m *Extra) String() string { return proto.CompactTextString(m) }
func (*Extra) ProtoMessage()    {}
func (*Extra) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *Extra) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Extra.Unmarshal(m, b)
}
func (m *Extra) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Extra.Marshal(b, m, deterministic)
}
func (m *Extra) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Extra.Merge(m, src)
}
func (m *Extra) XXX_Size() int {
	return xxx_messageInfo_Extra.Size(m)
}
func (m *Extra) XXX_DiscardUnknown() {
	xxx_messageInfo_Extra.DiscardUnknown(m)
}

var xxx_messageInfo_Extra proto.InternalMessageInfo

func (m *Extra) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *Extra) GetCurrentPage() int64 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *Extra) GetTotalPages() int64 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *Extra) GetIsFirst() bool {
	if m != nil {
		return m.IsFirst
	}
	return false
}

func (m *Extra) GetIsLast() bool {
	if m != nil {
		return m.IsLast
	}
	return false
}

func init() {
	proto.RegisterEnum("user.Channel", Channel_name, Channel_value)
	proto.RegisterEnum("user.Type", Type_name, Type_value)
	proto.RegisterType((*AddRequest)(nil), "user.AddRequest")
	proto.RegisterType((*UpdateRequest)(nil), "user.UpdateRequest")
	proto.RegisterType((*EnableRequest)(nil), "user.EnableRequest")
	proto.RegisterType((*DisableRequest)(nil), "user.DisableRequest")
	proto.RegisterType((*LoginRequest)(nil), "user.LoginRequest")
	proto.RegisterType((*ListRequest)(nil), "user.ListRequest")
	proto.RegisterType((*Response)(nil), "user.Response")
	proto.RegisterType((*UserResponse)(nil), "user.UserResponse")
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Extra)(nil), "user.Extra")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 712 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x54, 0x4b, 0x6f, 0xd3, 0x5c,
	0x10, 0xad, 0x1f, 0x79, 0x74, 0xdc, 0x44, 0xfe, 0xe6, 0xab, 0x90, 0x15, 0xa1, 0x36, 0x78, 0x43,
	0xa8, 0x44, 0x2a, 0xca, 0x86, 0x05, 0x1b, 0x37, 0x38, 0x0f, 0x35, 0x71, 0xda, 0x1b, 0x57, 0x5d,
	0x46, 0x4e, 0x7c, 0x1b, 0x2c, 0x25, 0x71, 0xf0, 0xbd, 0x01, 0xba, 0xe2, 0x27, 0x20, 0xd6, 0xec,
	0xd8, 0xb3, 0xe6, 0xef, 0x21, 0x5f, 0xdb, 0xad, 0x23, 0xd2, 0xc2, 0xb2, 0x3b, 0xcf, 0x99, 0x39,
	0xa3, 0xe3, 0xb9, 0x33, 0x07, 0x60, 0xcd, 0x68, 0xd4, 0x5c, 0x45, 0x21, 0x0f, 0x51, 0x8d, 0xbf,
	0x6b, 0x87, 0xb3, 0x30, 0x9c, 0xcd, 0xe9, 0xb1, 0xc0, 0x26, 0xeb, 0xeb, 0x63, 0x1e, 0x2c, 0x28,
	0xe3, 0xde, 0x62, 0x95, 0x94, 0x99, 0x5f, 0x25, 0x00, 0xcb, 0xf7, 0x09, 0xfd, 0xb0, 0xa6, 0x8c,
	0xe3, 0x53, 0xd8, 0x9d, 0x87, 0xb3, 0x60, 0xe9, 0x78, 0x0b, 0x6a, 0x48, 0x75, 0xa9, 0xb1, 0x4b,
	0xee, 0x00, 0xac, 0x41, 0x79, 0xe5, 0x31, 0xf6, 0x29, 0x8c, 0x7c, 0x43, 0x16, 0xc9, 0xdb, 0x18,
	0x9f, 0x43, 0x69, 0xfa, 0xde, 0x5b, 0x2e, 0xe9, 0xdc, 0x50, 0xea, 0x52, 0xa3, 0x7a, 0x52, 0x69,
	0x0a, 0x35, 0xad, 0x04, 0x24, 0x59, 0x16, 0x0f, 0x40, 0xe5, 0x37, 0x2b, 0x6a, 0xa8, 0xa2, 0x0a,
	0x92, 0x2a, 0xf7, 0x66, 0x45, 0x89, 0xc0, 0xcd, 0x1f, 0x12, 0x54, 0x2e, 0x57, 0xbe, 0xc7, 0x69,
	0x26, 0xaa, 0x0a, 0x72, 0xe0, 0x0b, 0x35, 0x0a, 0x91, 0x03, 0x7f, 0x53, 0xa4, 0xfc, 0x90, 0x48,
	0xe5, 0x7e, 0x91, 0xea, 0x3f, 0x89, 0x2c, 0xdc, 0x23, 0xf2, 0x10, 0x2a, 0xf6, 0xd2, 0x9b, 0xcc,
	0xef, 0xd3, 0x68, 0xd6, 0xa1, 0xfa, 0x2e, 0x60, 0x0f, 0x55, 0x7c, 0x93, 0x60, 0xaf, 0x1f, 0xab,
	0x7e, 0x44, 0xb3, 0xaf, 0x80, 0xd6, 0x0f, 0x18, 0x4f, 0x15, 0x99, 0x6f, 0xa0, 0x4c, 0x28, 0x5b,
	0x85, 0x4b, 0x46, 0x11, 0x41, 0x9d, 0x86, 0x7e, 0x22, 0xac, 0x42, 0xc4, 0x37, 0x1a, 0x50, 0x5a,
	0x50, 0xc6, 0xbc, 0x59, 0xf6, 0x0c, 0x59, 0x68, 0x7e, 0x81, 0xbd, 0x4b, 0x46, 0xa3, 0x07, 0xd9,
	0x07, 0xa0, 0x4e, 0x42, 0xff, 0xc6, 0x90, 0xeb, 0x4a, 0x43, 0xcb, 0xc4, 0x08, 0x96, 0xc0, 0xf3,
	0xdd, 0x95, 0x8d, 0xee, 0xf8, 0x0c, 0x0a, 0xf4, 0x33, 0x8f, 0x3c, 0xf1, 0x1f, 0xda, 0x89, 0x96,
	0x50, 0xed, 0x18, 0x22, 0x49, 0xc6, 0xfc, 0x25, 0x83, 0x1a, 0xf7, 0x7a, 0x84, 0xcb, 0x83, 0x4f,
	0xa0, 0xc8, 0xb8, 0xc7, 0xd7, 0xcc, 0x28, 0xd6, 0xa5, 0x46, 0x99, 0xa4, 0x11, 0xbe, 0x05, 0x6d,
	0x1a, 0x51, 0x8f, 0x53, 0xdf, 0x0d, 0x16, 0xd4, 0x28, 0x89, 0x9f, 0xab, 0x35, 0x93, 0x13, 0x6e,
	0x66, 0x27, 0xdc, 0x74, 0xb3, 0x13, 0x26, 0xf9, 0x72, 0x6c, 0x83, 0x3e, 0xf7, 0x18, 0x1f, 0x84,
	0x7e, 0x70, 0x1d, 0xa4, 0x2d, 0xca, 0x7f, 0x6d, 0xf1, 0x07, 0xc7, 0xfc, 0x2e, 0x41, 0x41, 0x8c,
	0x12, 0x0f, 0x00, 0x78, 0xc8, 0xbd, 0x79, 0x2b, 0x5c, 0x2f, 0x79, 0x3a, 0xc2, 0x1c, 0x82, 0x75,
	0xd0, 0xa6, 0xeb, 0x28, 0xa2, 0x4b, 0x7e, 0x9e, 0xad, 0x80, 0x42, 0xf2, 0xd0, 0x6d, 0x87, 0x38,
	0x60, 0x62, 0xa0, 0x59, 0x07, 0x81, 0xc4, 0x4f, 0x1c, 0xb0, 0x76, 0x10, 0x31, 0x2e, 0x46, 0x5a,
	0x26, 0x59, 0x18, 0xcf, 0x28, 0x60, 0x7d, 0x8f, 0x71, 0x31, 0xc5, 0x32, 0x49, 0xa3, 0xa3, 0x2b,
	0x28, 0xa5, 0xf3, 0xc6, 0x3d, 0x28, 0x13, 0xbb, 0xd3, 0x1b, 0xb9, 0x36, 0xd1, 0x77, 0xe2, 0xa8,
	0x6d, 0xb5, 0xec, 0xd3, 0xe1, 0xf0, 0x4c, 0x97, 0xe2, 0xe8, 0xaa, 0x6b, 0xb9, 0x23, 0xeb, 0xfc,
	0x5c, 0x97, 0xb1, 0x02, 0xbb, 0x3d, 0x67, 0xe4, 0x5a, 0x1d, 0x62, 0x0d, 0x74, 0x05, 0x35, 0x28,
	0x5d, 0xd9, 0xad, 0xae, 0x45, 0x5c, 0x5d, 0xc5, 0x22, 0xc8, 0x17, 0x17, 0x7a, 0xe1, 0x68, 0x08,
	0x6a, 0xfc, 0x44, 0x58, 0x05, 0x18, 0x58, 0x8e, 0xd5, 0xb1, 0x07, 0xb6, 0xe3, 0xea, 0x3b, 0x31,
	0x77, 0xd4, 0x1d, 0x12, 0x77, 0x7c, 0x49, 0xfa, 0xba, 0x84, 0xfb, 0xa0, 0xf7, 0x6d, 0x8b, 0x38,
	0x3d, 0xa7, 0x33, 0xb6, 0x9d, 0x4e, 0xbf, 0x37, 0xea, 0xea, 0x32, 0x22, 0x54, 0x4f, 0x2d, 0xd7,
	0xed, 0xdb, 0xe3, 0x61, 0x7b, 0xec, 0x5a, 0xce, 0x99, 0xae, 0x9c, 0xfc, 0x94, 0x41, 0x8b, 0x37,
	0x70, 0x44, 0xa3, 0x8f, 0xc1, 0x94, 0xe2, 0x0b, 0x50, 0x2c, 0xdf, 0x47, 0x3d, 0x59, 0x87, 0x3b,
	0xcf, 0xad, 0x55, 0x13, 0x24, 0xbb, 0x15, 0x73, 0x07, 0x8f, 0xa1, 0x98, 0x38, 0x20, 0xfe, 0x9f,
	0x5e, 0x45, 0xde, 0x0f, 0xb7, 0x13, 0x12, 0x3b, 0xca, 0x08, 0x1b, 0xe6, 0xb4, 0x85, 0xf0, 0x0a,
	0x4a, 0xa9, 0x3d, 0xe1, 0x7e, 0x92, 0xdc, 0x74, 0xab, 0x2d, 0x94, 0x97, 0x50, 0x10, 0x76, 0x85,
	0x98, 0xa4, 0xf2, 0xde, 0xb5, 0x55, 0x92, 0x1a, 0x5b, 0x09, 0xfe, 0x97, 0x56, 0xdf, 0xd9, 0x4a,
	0x0d, 0x73, 0xa7, 0x7e, 0x4b, 0x98, 0x14, 0xc5, 0x76, 0xbe, 0xfe, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0xcb, 0x6e, 0x9e, 0xa9, 0xc5, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Response, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Response, error)
	Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*Response, error)
	Disable(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*Response, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error)
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/user.UserService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/user.UserService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Enable(ctx context.Context, in *EnableRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/user.UserService/Enable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Disable(ctx context.Context, in *DisableRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/user.UserService/Disable", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/user.UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user.UserService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	Add(context.Context, *AddRequest) (*Response, error)
	Update(context.Context, *UpdateRequest) (*Response, error)
	Enable(context.Context, *EnableRequest) (*Response, error)
	Disable(context.Context, *DisableRequest) (*Response, error)
	Login(context.Context, *LoginRequest) (*Response, error)
	List(context.Context, *ListRequest) (*UserResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) Add(ctx context.Context, req *AddRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedUserServiceServer) Update(ctx context.Context, req *UpdateRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUserServiceServer) Enable(ctx context.Context, req *EnableRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enable not implemented")
}
func (*UnimplementedUserServiceServer) Disable(ctx context.Context, req *DisableRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Disable not implemented")
}
func (*UnimplementedUserServiceServer) Login(ctx context.Context, req *LoginRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserServiceServer) List(ctx context.Context, req *ListRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Enable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Enable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Enable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Enable(ctx, req.(*EnableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Disable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Disable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Disable",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Disable(ctx, req.(*DisableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.UserService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _UserService_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "Enable",
			Handler:    _UserService_Enable_Handler,
		},
		{
			MethodName: "Disable",
			Handler:    _UserService_Disable_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "List",
			Handler:    _UserService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
